### ISSUE TITLE
`dapple test` broken

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#51]
```
TypeError: provider.manager.blockchain.setGasLimit is not a function
    at Object.module.exports.EVM (/Users/nikolai/devenv/dapple/lib/web3Factory.js:33:37)
    at DestroyableTransform._transform (/Users/nikolai/devenv/dapple/lib/streams.js:177:36)
    at DestroyableTransform.Transform._read (/Users/nikolai/devenv/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/nikolai/devenv/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/nikolai/devenv/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/Users/nikolai/devenv/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/Users/nikolai/devenv/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at Stream.method [as write] (/Users/nikolai/devenv/dapple/node_modules/duplexer/index.js:47:39)
    at DestroyableTransform.ondata (/Users/nikolai/devenv/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:581:20)
    at emitOne (events.js:77:13)
```

**Comment by ryepdx** [comment]
Ah, yeah. You're going to need to reinstall EtherSim from package.json. I switched the dependency from a version number to the URL for my fork of it. So `npm install ` should fix that for you.

**Comment by nmushegian** [comment]
`npm install` doesn't seem to force reinstall, you have to delete node_modules or at least the specific module:  https://github.com/npm/npm/issues/5254

But even after deleting local and even global node_modules, it still doesn't work =\

**Comment by nmushegian** [comment]
Yep for some reason it's still pulling an old version of ethersim. Investigating...

**Comment by nmushegian** [comment]
Your default branch is develop, but npm always pulls from master.
Maybe a good opportunity to move the fork into the company org?
